site_name: Virtual Motion Tracker
site_description: The OSC Virtual OpenVR Tracker Driver for your DIY tracking devices.
site_url: https://gpsnmeajp.github.io/VirtualMotionTrackerDocument/
repo_url: https://github.com/gpsnmeajp/VirtualMotionTracker/
repo_name: VirtualMotionTracker
nav:
    - Home: index.md
    - Setup: setup.md
    - Trouble: trouble.md
    - API: api.md
    - Download: download.md
theme:
  name: material
  custom_dir: overrides
  logo: img/Ready32x32.png
  favicon: img/Ready32x32.png
  features:
    - navigation.tabs
    - navigation.instant
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
extra_css:
    - stylesheets/extra.css
markdown_extensions:
  - meta
  - admonition
  - toc:
      permalink: ⚓︎
      toc_depth: 3
