site_name: Virtual Motion Tracker
site_description: The OSC Virtual OpenVR Tracker Driver for your DIY tracking devices.
site_url: https://gpsnmeajp.github.io/VirtualMotionTrackerDocument/
edit_uri: ""
repo_url: https://github.com/gpsnmeajp/VirtualMotionTracker/
repo_name: VirtualMotionTracker
nav:
    - Home: index.md
    - How it works: howitworks.md
    - Setup: setup.md
    - Trouble: trouble.md
    - Advanced: advanced.md
    - API: api.md
    - Download: download.md
    - Report: report.md
theme:
  name: material
  custom_dir: overrides
  logo: image/Ready32x32.png
  favicon: image/Ready32x32.png
  features:
    - navigation.tabs
  palette:
    - scheme: slate
extra_css:
    - stylesheets/extra.css
markdown_extensions:
  - meta
  - admonition
  - toc:
      permalink: ⚓︎
      toc_depth: 3
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
